name: example02
on:
  workflow_dispatch:
    inputs:
      loglevel:
        description: "Log Level"
        required: true
        default: "warning"
        type: choice
        options:
          - info
          - warnings
          - debug
        print_tags:
          description: "True to print to STDOUT"
          required: true
          type: boolean
        tags:
          description: "Test Scenarios tags"
          required: true
          type: string

jobs:
  Explore-Github-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo " Tags - ${{ inputs.tags }} loglevel - ${{ inputs.loglevel }} "
