name: Example Workflow 11
on: [workflow_dispatch]
jobs:
  Stage1:
    runs-on: ubuntu-latest
    steps:
      - run: touch new.txt
      - run: ls -l
      - name: Upload Text file
        uses: actions/upload-artifact@v4
        with:
          name: files
          path: new.txt
   Stage2:
     runs-on: ubuntu-latest
     steps:
       - name: Download files
         uses: actions/download-artifact@v4
         with:
           name: files
       - run: ls -l
